module(
    name = "envoy-examples",
    version = "0.2.6",
)

bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "envoy", version = "1.40.0-dev.20260903.6609c01.envoy")
bazel_dep(name = "envoy-example-filter-cc", version = "0.2.6")
bazel_dep(name = "envoy-example-wasm-cc", version = "0.2.6")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "rules_python", version = "2.2.0")
bazel_dep(name = "rules_shell", version = "0.8.0")

bazel_dep(name = "toolchains_llvm", version = "1.9.0.envoy", dev_dependency = True)

envoy_toolchains_ext = use_extension("@envoy//bazel:extensions.bzl", "envoy_toolchains_extension")
use_repo(envoy_toolchains_ext, "clang_platform")

# local_path_override(
#     module_name = "envoy",
#     path = "../envoy",
# )
#
# local_path_override(
#     module_name = "envoy_api",
#     path = "../envoy/api",
# )

local_path_override(
    module_name = "envoy-example-filter-cc",
    path = "filter-cc",
)

local_path_override(
    module_name = "envoy-example-wasm-cc",
    path = "wasm-cc",
)
