services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    depends_on:
    - web_service
    ports:
    - "8000:8000"
    - "8001:8001"

  web_service:
    image: envoy-example-echo
    build:
      context: ../shared/echo
