workspace(name = "envoy_examples_wasmcc")

load(":archives.bzl", "load_archives")
load_archives()

load(":deps.bzl", "resolve_dependencies")
resolve_dependencies()

load(":toolchains.bzl", "load_toolchains")
load_toolchains()

load(":packages.bzl", "load_packages")
load_packages()
