services:
  envoy:
    build:
      context: .
      dockerfile: ../shared/envoy/Dockerfile
    ports:
    - "${PORT_PROXY:-10000}:10000"
    - "${PORT_ADMIN:-10001}:10001"

  backend:
    image: ${COMPOSE_PROJECT_NAME}-echo
    build:
      context: ../shared/echo
