services:

  proxy:
    build:
      context: .
      dockerfile: ../shared/envoy/Dockerfile
      target: envoy-dynamic-fs
    depends_on:
    - service1
    - service2
    ports:
    - "${PORT_PROXY:-10000}:10000"
    - "${PORT_ADMIN:-19000}:19000"

  service1:
    image: ${COMPOSE_PROJECT_NAME}-echo
    build:
      context: ../shared/echo
    environment:
      ECHO_HOSTNAME: service1

  service2:
    image: ${COMPOSE_PROJECT_NAME}-echo
    build:
      context: ../shared/echo
    environment:
      ECHO_HOSTNAME: service2
