services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-10000}:10000"

  backend:
    build:
      context: ../shared/echo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 3s
      retries: 3
