name: Verify/Examples

permissions:
  contents: read

on:
  workflow_call:


jobs:
  examples:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        bazel-mode: [workspace, bzlmod]
    steps:
    - uses: envoyproxy/toolshed/actions/bind-mounts@598eacce15ab5f208102a2fd5669292868002701  # v0.4.0
      with:
        mounts: |
          - src: /mnt/docker
            target: /var/lib/docker
            rm: true
            command-pre: sudo systemctl stop docker
            command-post: sudo systemctl start docker
          - src: /mnt/runner-cache
            target: /home/runner/.cache
            chown: "runner:runner"
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        path: examples
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      if: matrix.bazel-mode == 'bzlmod'
      with:
        repository: envoyproxy/envoy
        ref: bzlmod-envoy-head
        path: envoy
    - run: |
        TEMPDIR=/cache/docker
        sudo mkdir -p "${TEMPDIR}"
        sudo mount -t tmpfs none "$TEMPDIR"
        sudo chown runner "$TEMPDIR"
    - uses: actions/cache/restore@v6
      id: cache
      with:
        path: /cache/docker
        key: ${{ runner.os }}-docker-${{ matrix.bazel-mode }}-${{ hashFiles('examples/**/Dockerfile*') }}
    - run: |
        TEMPDIR=/cache/docker
        sudo mkdir -p /var/lib/docker-examples
        zstd --stdout -d "${TEMPDIR}/docker.tar.zst" | sudo tar --warning=no-timestamp -xf - -C /var/lib/docker-examples
        sudo umount "$TEMPDIR"
      if: steps.cache.outputs.cache-hit == 'true'
    - run: |
        TEMPDIR=/cache/docker
        sudo mkdir -p "${TEMPDIR}"
        sudo mount -t tmpfs none "$TEMPDIR"
        sudo chown runner "$TEMPDIR"
        sudo du -ch /var/lib/docker | grep total
        sudo du -ch /var/lib/docker-examples | grep total
        sudo df -h
    - uses: actions/cache@v6
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-bazel-${{ matrix.bazel-mode }}-${{ hashFiles('examples/**/BUILD', 'examples/**/*bzl', 'examples/WORKSPACE') }}

    - run: |
        docker pull envoyproxy/envoy:dev
        DEV_CONTAINER_ID=$(docker inspect --format='{{.Id}}' envoyproxy/envoy:dev)
        echo "DEV_CONTAINER_ID=${DEV_CONTAINER_ID}" >> $GITHUB_ENV
    - run: |
        export UID
        printf '%s\n' 'common --config=ci' > repo.bazelrc
        if [ "${BAZEL_MODE}" = "bzlmod" ]; then
          echo "common --enable_bzlmod" >> repo.bazelrc
        fi
        docker compose run --quiet --quiet-pull --quiet-build examples
      working-directory: examples
      env:
        BAZEL_MODE: ${{ matrix.bazel-mode }}
        DOCKER_BUILDKIT: 1
        COMPOSE_BAKE: true
        BUILDKIT_PROGRESS: quiet

    - run: |
        TEMPDIR=/cache/docker
        sudo tar cf - -C /var/lib/docker-examples . | zstd - -q -T0 -o "${TEMPDIR}/docker.tar.zst"
        ls -alh "${TEMPDIR}/docker.tar.zst"
      if: steps.cache.outputs.cache-hit != 'true' && github.event_name != 'pull_request'
    - uses: actions/cache/save@v6
      if: steps.cache.outputs.cache-hit != 'true' && github.event_name != 'pull_request'
      with:
        path: /cache/docker
        key: ${{ runner.os }}-docker-${{ matrix.bazel-mode }}-${{ hashFiles('examples/**/Dockerfile*') }}
