name: Verify/Wasm

permissions:
  contents: read

on:
  workflow_call:


jobs:
  wasm:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - run: |
        docker pull envoyproxy/envoy:dev
        DEV_CONTAINER_ID=$(docker inspect --format='{{.Id}}' envoyproxy/envoy:dev)
        echo "DEV_CONTAINER_ID=${DEV_CONTAINER_ID}" >> $GITHUB_ENV
    - run: |
        ./verify.sh
      working-directory: wasm-cc
