name: DCO

on:
  merge_group:

permissions:
  contents: read

jobs:
  DCO:
    runs-on: ubuntu-24.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
    - run: echo "Skip DCO for merge queue"
