name: Docs

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: >-
    ${{ github.event.inputs.head_ref || github.run_id }}


jobs:
  docs:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        repository: envoyproxy/envoy
        path: envoy

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        path: examples
    - name: RBE auth check
      id: rbe
      if: github.event_name == 'pull_request'
      uses: envoyproxy/toolshed/actions/github/container/auth@f6cc2e99964fcec26d4e497d7e41cca502e7241e
      with:
        container: hello-world
    - name: Configure repo Bazel settings (base)
      working-directory: envoy
      run: |
        cat > repo.bazelrc <<'EOF'
        common --config=remote-ci
        EOF
        cat repo.bazelrc
    - name: Configure repo Bazel settings (RBE/BES)
      if: >-
        github.event_name != 'pull_request'
        || steps.rbe.outputs.authorized == 'true'
      working-directory: envoy
      run: |
        cat >> repo.bazelrc <<'EOF'
        common --config=rbe
        common --config=bes
        EOF
        cat repo.bazelrc
    - name: Build docs
      run: |
        export UID
        export GID=$(id -g)

        docker compose run docs
      working-directory: examples
      env:
        BUILDKIT_PROGRESS: quiet
        COMPOSE_BAKE: true
        DOCKER_BUILDKIT: 1
        GITHUB_TOKEN: ${{ github.token }}

    - name: Docs upload
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: docs
        path: envoy/generated/docs
        retention-days: 30
