name: Verify

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: >-
    ${{ github.event.inputs.head_ref || github.run_id }}


jobs:
  examples:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_verify_examples.yml
  build:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_verify_build.yml
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        example:
        - wasm-cc
        - filter-cc
    with:
      example: ${{ matrix.example }}
